/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/new_house.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/new_house.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Kasten002_Cube018.geometry} material={materials.holz} />
      <mesh geometry={nodes.Plane015_Plane027.geometry} material={materials.chrom} />
      <mesh geometry={nodes.Plane014_Plane026.geometry} material={materials.maror} />
      <mesh geometry={nodes.Cylinder001_Cylinder007.geometry} material={materials.blau} />
      <mesh geometry={nodes.Cylinder_Cylinder006.geometry} material={materials.rot} />
      <mesh geometry={nodes.Cube005_Cube014.geometry} material={materials.chrom} />
      <mesh geometry={nodes.Cube004_Cube012.geometry} material={materials.chrom} />
      <mesh geometry={nodes.Cube003_Cube008.geometry} material={materials.chrom} />
      <mesh geometry={nodes.Plane013_Plane025.geometry} material={materials.weiß} />
      <mesh geometry={nodes.Plane012_Plane024.geometry} material={materials['Glas-2']} />
      <mesh geometry={nodes.Plane011_Plane023.geometry} material={materials['Glas-2']} />
      <mesh geometry={nodes.Plane010_Plane022.geometry} material={materials.weiß} />
      <mesh geometry={nodes.Plane009_Plane021.geometry} material={materials.fliesen2} />
      <mesh geometry={nodes.Plane008_Plane020.geometry} material={materials.weiß} />
      <mesh geometry={nodes.Plane007_Plane019.geometry} material={materials['Glas-2']} />
      <mesh geometry={nodes.Plane006_Plane018.geometry} material={materials.lack} />
      <mesh geometry={nodes.Übergang002_Plane017.geometry} material={materials.silber} />
      <mesh geometry={nodes.Plane005_Plane016.geometry} material={materials.holz1} />
      <mesh geometry={nodes.Plane004_Plane013.geometry} material={materials.lack} />
      <mesh geometry={nodes.Plane003_Plane012.geometry} material={materials.None} />
      <mesh geometry={nodes.Plane002_Plane011.geometry} material={materials.lack} />
      <mesh geometry={nodes.Plane001_Plane010.geometry} material={materials.None} />
      <mesh geometry={nodes.Cube002_Cube013.geometry} material={materials.stoff1} />
      <mesh geometry={nodes.Cube001_Cube011.geometry} material={materials.stoff1} />
      <mesh geometry={nodes.Cube_Cube010.geometry} material={materials.stoff2} />
      <mesh geometry={nodes.Bett_Plane009.geometry} material={materials.holz} />
      <mesh geometry={nodes.Plane_Plane014.geometry} material={materials.stoff1} />
      <mesh geometry={nodes.Schutz002_Cylinder003.geometry} material={materials.gummi} />
      <mesh geometry={nodes.Übergang001_Plane008.geometry} material={materials.silber} />
      <mesh geometry={nodes.Übergang_Plane004.geometry} material={materials.silber} />
      <mesh geometry={nodes.Boden2_Plane007.geometry} material={materials['holz1_Holz_weiß.jpg']} />
      <mesh geometry={nodes.Boden1_Plane005.geometry} material={materials.holz1} />
      <mesh geometry={nodes.Wand_Plane001.geometry} material={materials.wand3} />
      <mesh geometry={nodes.Michael_Text.geometry} material={materials.chrom} />
      <mesh geometry={nodes.Ständer2_Cube005.geometry} material={materials.schwarz} />
      <mesh geometry={nodes.Ständer_Cube.geometry} material={materials.chrom} />
      <mesh geometry={nodes.Kasten001_Cube004.geometry} material={materials.holz} />
      <mesh geometry={nodes.Kasten_Cube003.geometry} material={materials.holz} />
      <mesh geometry={nodes.Schutz001_Cylinder001.geometry} material={materials.gummi} />
      <mesh geometry={nodes.Tischplatte_Cube002.geometry} material={materials['Glas-2']} />
      <mesh geometry={nodes.Tischbein_Cube001.geometry} material={materials.holz} />
      <mesh geometry={nodes.Schutz_Cylinder.geometry} material={materials.gummi} />
      <mesh geometry={nodes.Fliesen_Plane.geometry} material={materials.Fliesen} />
      <mesh geometry={nodes.Teppich_Plane002.geometry} material={materials.stoff} />
      <mesh geometry={nodes['Plane016_Plane028-Mesh'].geometry} material={materials.lack} />
      <mesh geometry={nodes['Plane016_Plane028-Mesh_1'].geometry} material={materials.glas_matt} />
      <mesh geometry={nodes['bild002_Cube019-Mesh'].geometry} material={materials.plastik} />
      <mesh geometry={nodes['bild002_Cube019-Mesh_1'].geometry} material={materials.picture2} />
      <mesh geometry={nodes['bild002_Cube019-Mesh_2'].geometry} material={materials.Glas} />
      <mesh geometry={nodes['Cube006_Cube015-Mesh'].geometry} material={materials.chrom} />
      <mesh geometry={nodes['Cube006_Cube015-Mesh_1'].geometry} material={materials['Glas-2']} />
      <mesh geometry={nodes['Wand001_Plane015-Mesh'].geometry} material={materials.wand2} />
      <mesh geometry={nodes['Wand001_Plane015-Mesh_1'].geometry} material={materials.fliesen2} />
      <mesh geometry={nodes['Wand1_Plane006-Mesh'].geometry} material={materials.wand} />
      <mesh geometry={nodes['Wand1_Plane006-Mesh_1'].geometry} material={materials.brick} />
      <mesh geometry={nodes['Wand1_Plane006-Mesh_2'].geometry} material={materials.fliesen2} />
      <mesh geometry={nodes['Fenster_Plane003-Mesh'].geometry} material={materials.holz} />
      <mesh geometry={nodes['Fenster_Plane003-Mesh_1'].geometry} material={materials.Glas} />
      <mesh geometry={nodes['Glas002_Cylinder005-Mesh'].geometry} material={materials['Glas-2']} />
      <mesh geometry={nodes['Glas002_Cylinder005-Mesh_1'].geometry} material={materials.eistee} />
      <mesh geometry={nodes['Glas001_Cylinder004-Mesh'].geometry} material={materials.eistee} />
      <mesh geometry={nodes['Glas001_Cylinder004-Mesh_1'].geometry} material={materials['Glas-2']} />
      <mesh geometry={nodes['Glas_Cylinder002-Mesh'].geometry} material={materials.eistee} />
      <mesh geometry={nodes['Glas_Cylinder002-Mesh_1'].geometry} material={materials['Glas-2']} />
      <mesh geometry={nodes['bild001_Cube009-Mesh'].geometry} material={materials.plastik} />
      <mesh geometry={nodes['bild001_Cube009-Mesh_1'].geometry} material={materials.picture2} />
      <mesh geometry={nodes['bild001_Cube009-Mesh_2'].geometry} material={materials.Glas} />
      <mesh geometry={nodes['bild_Cube007-Mesh'].geometry} material={materials.gold} />
      <mesh geometry={nodes['bild_Cube007-Mesh_1'].geometry} material={materials.picture1} />
      <mesh geometry={nodes['bild_Cube007-Mesh_2'].geometry} material={materials.plastik} />
      <mesh geometry={nodes['bild_Cube007-Mesh_3'].geometry} material={materials.Glas} />
      <mesh geometry={nodes['Fernseher_Cube006-Mesh'].geometry} material={materials.schwarz} />
      <mesh geometry={nodes['Fernseher_Cube006-Mesh_1'].geometry} material={materials.blidschirm} />
    </group>
  )
}

useGLTF.preload('/new_house.glb')
