/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/new_house.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, CuboidCollider } from '@react-three/rapier'

export default function House(props) {
  const { nodes, materials } = useGLTF('/new_house.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Kasten002_Cube018.geometry} >
        <meshStandardMaterial color="#8B4513" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane015_Plane027.geometry} >
        <meshStandardMaterial color="#cccccc" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane014_Plane026.geometry} >
        <meshStandardMaterial color="#ffffff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cylinder001_Cylinder007.geometry} >
        <meshStandardMaterial color="#0000ff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_Cylinder006.geometry} >
        <meshStandardMaterial color="#ff0000" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube005_Cube014.geometry} >
        <meshStandardMaterial color="#cccccc" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube004_Cube012.geometry} >
        <meshStandardMaterial color="#cccccc" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube003_Cube008.geometry} >
        <meshStandardMaterial color="#cccccc" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane013_Plane025.geometry} >
        <meshStandardMaterial color="#ffffff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane012_Plane024.geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane011_Plane023.geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane010_Plane022.geometry} >
        <meshStandardMaterial color="#ffffff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane009_Plane021.geometry} >
        <meshStandardMaterial color="#dddddd" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane008_Plane020.geometry} >
        <meshStandardMaterial color="#ffffff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane007_Plane019.geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane006_Plane018.geometry} >
        <meshStandardMaterial color="#222222" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Übergang002_Plane017.geometry} >
        <meshStandardMaterial color="#c0c0c0" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane005_Plane016.geometry} >
        <meshStandardMaterial color="#A0522D" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane004_Plane013.geometry} >
        <meshStandardMaterial color="#222222" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane003_Plane012.geometry} >
        <meshStandardMaterial color="#888888" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane002_Plane011.geometry} >
        <meshStandardMaterial color="#222222" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane001_Plane010.geometry} >
        <meshStandardMaterial color="#888888" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube002_Cube013.geometry} >
        <meshStandardMaterial color="#bbbbbb" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube001_Cube011.geometry} >
        <meshStandardMaterial color="#bbbbbb" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube_Cube010.geometry} >
        <meshStandardMaterial color="#999999" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Bett_Plane009.geometry} >
        <meshStandardMaterial color="#8B4513" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane_Plane014.geometry} >
        <meshStandardMaterial color="#bbbbbb" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Schutz002_Cylinder003.geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Übergang001_Plane008.geometry} >
        <meshStandardMaterial color="#c0c0c0" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Übergang_Plane004.geometry} >
        <meshStandardMaterial color="#c0c0c0" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Boden2_Plane007.geometry} >
        <meshStandardMaterial color="#ffffff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Boden1_Plane005.geometry} >
        <meshStandardMaterial color="#A0522D" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Wand_Plane001.geometry} >
        <meshStandardMaterial color="#f0f0f0" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Michael_Text.geometry} >
        <meshStandardMaterial color="#cccccc" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Ständer2_Cube005.geometry} >
        <meshStandardMaterial color="#000000" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Ständer_Cube.geometry} >
        <meshStandardMaterial color="#cccccc" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Kasten001_Cube004.geometry} >
        <meshStandardMaterial color="#8B4513" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Kasten_Cube003.geometry} >
        <meshStandardMaterial color="#8B4513" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Schutz001_Cylinder001.geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Tischplatte_Cube002.geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Tischbein_Cube001.geometry} >
        <meshStandardMaterial color="#8B4513" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Schutz_Cylinder.geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Fliesen_Plane.geometry} >
        <meshStandardMaterial color="#aaaaaa" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Teppich_Plane002.geometry} >
        <meshStandardMaterial color="#888888" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Plane016_Plane028-Mesh'].geometry} >
        <meshStandardMaterial color="#222222" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Plane016_Plane028-Mesh_1'].geometry} >
        <meshStandardMaterial color="#dddddd" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild002_Cube019-Mesh'].geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild002_Cube019-Mesh_1'].geometry} >
        <meshStandardMaterial color="#444444" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild002_Cube019-Mesh_2'].geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Cube006_Cube015-Mesh'].geometry} >
        <meshStandardMaterial color="#cccccc" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Cube006_Cube015-Mesh_1'].geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Wand001_Plane015-Mesh'].geometry} >
        <meshStandardMaterial color="#e0e0e0" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Wand001_Plane015-Mesh_1'].geometry} >
        <meshStandardMaterial color="#dddddd" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Wand1_Plane006-Mesh'].geometry} >
        <meshStandardMaterial color="#ffffff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Wand1_Plane006-Mesh_1'].geometry} >
        <meshStandardMaterial color="#b22222" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Wand1_Plane006-Mesh_2'].geometry} >
        <meshStandardMaterial color="#dddddd" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Fenster_Plane003-Mesh'].geometry} >
        <meshStandardMaterial color="#8B4513" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Fenster_Plane003-Mesh_1'].geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas002_Cylinder005-Mesh'].geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas002_Cylinder005-Mesh_1'].geometry} >
        <meshStandardMaterial color="#d2691e" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas001_Cylinder004-Mesh'].geometry} >
        <meshStandardMaterial color="#d2691e" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas001_Cylinder004-Mesh_1'].geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas_Cylinder002-Mesh'].geometry} >
        <meshStandardMaterial color="#d2691e" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas_Cylinder002-Mesh_1'].geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild001_Cube009-Mesh'].geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild001_Cube009-Mesh_1'].geometry} >
        <meshStandardMaterial color="#444444" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild001_Cube009-Mesh_2'].geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild_Cube007-Mesh'].geometry} >
        <meshStandardMaterial color="#ffd700" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild_Cube007-Mesh_1'].geometry} >
        <meshStandardMaterial color="#555555" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild_Cube007-Mesh_2'].geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild_Cube007-Mesh_3'].geometry} >
        <meshStandardMaterial color="#aaccff" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Fernseher_Cube006-Mesh'].geometry} >
        <meshStandardMaterial color="#000000" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Fernseher_Cube006-Mesh_1'].geometry} >
        <meshStandardMaterial color="#000000" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/new_house.glb')
