/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/new_house.glb 
*/

import React, { useRef, useMemo } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF, Text, useTexture } from '@react-three/drei'
import * as THREE from 'three'
import { RigidBody, CuboidCollider } from '@react-three/rapier'

export default function House(props) {

  const { nodes, materials } = useGLTF('/new_house.glb')
  
  const woodTextures = useTexture({
    map: '/textures/wood/color.jpg',
    bumpMap: '/textures/wood/bump.jpg',
    roughnessMap: '/textures/wood/roughness.jpg'
  });
  
  // Wrap textures so they tile correctly instead of stretching
  useMemo(() => {
    Object.values(woodTextures).forEach(tex => {
      tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
      tex.repeat.set(2, 2);
    });
  }, [woodTextures]);

  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Kasten002_Cube018.geometry} >
        <meshStandardMaterial {...woodTextures} bumpScale={0.01} color="#aa7755" />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane015_Plane027.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane014_Plane026.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cylinder001_Cylinder007.geometry} >
        <meshStandardMaterial color="#2c3e50" roughness={0.2} metalness={0.5} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_Cylinder006.geometry} >
        <meshStandardMaterial color="#c0392b" roughness={0.2} metalness={0.5} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube005_Cube014.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube004_Cube012.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube003_Cube008.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane013_Plane025.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane012_Plane024.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane011_Plane023.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane010_Plane022.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane009_Plane021.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane008_Plane020.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane007_Plane019.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane006_Plane018.geometry} >
        <meshStandardMaterial color="#222222" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Übergang002_Plane017.geometry} >
        <meshStandardMaterial color="#c0c0c0" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane005_Plane016.geometry} >
        <meshStandardMaterial color="#A0522D" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane004_Plane013.geometry} >
        <meshStandardMaterial color="#222222" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane003_Plane012.geometry} >
        <meshStandardMaterial color="#888888" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane002_Plane011.geometry} >
        <meshStandardMaterial color="#222222" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane001_Plane010.geometry} >
        <meshStandardMaterial color="#888888" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube002_Cube013.geometry} >
        <meshStandardMaterial color="#bbbbbb" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube001_Cube011.geometry} >
        <meshStandardMaterial color="#bbbbbb" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Cube_Cube010.geometry} >
        <meshStandardMaterial color="#999999" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Bett_Plane009.geometry} >
        <meshStandardMaterial {...woodTextures} bumpScale={0.01} color="#aa7755" />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Plane_Plane014.geometry} >
        <meshStandardMaterial color="#bbbbbb" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Schutz002_Cylinder003.geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Übergang001_Plane008.geometry} >
        <meshStandardMaterial color="#c0c0c0" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Übergang_Plane004.geometry} >
        <meshStandardMaterial color="#c0c0c0" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Boden2_Plane007.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Boden1_Plane005.geometry} >
        <meshStandardMaterial {...woodTextures} bumpScale={0.01} color="#885533" />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Wand_Plane001.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Michael_Text.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Ständer2_Cube005.geometry} >
        <meshStandardMaterial color="#111111" roughness={0.3} metalness={0.8} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Ständer_Cube.geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Kasten001_Cube004.geometry} >
        <meshStandardMaterial {...woodTextures} bumpScale={0.01} color="#aa7755" />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Kasten_Cube003.geometry} >
        <meshStandardMaterial {...woodTextures} bumpScale={0.01} color="#aa7755" />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Schutz001_Cylinder001.geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Tischplatte_Cube002.geometry} >
        <meshStandardMaterial color="#fafafa" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Tischbein_Cube001.geometry} >
        <meshStandardMaterial color="#111111" roughness={0.3} metalness={0.8} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Schutz_Cylinder.geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Fliesen_Plane.geometry} >
        <meshStandardMaterial color="#aaaaaa" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes.Teppich_Plane002.geometry} >
        <meshStandardMaterial color="#1a237e" roughness={1.0} metalness={0.0} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Plane016_Plane028-Mesh'].geometry} >
        <meshStandardMaterial color="#222222" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Plane016_Plane028-Mesh_1'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild002_Cube019-Mesh'].geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild002_Cube019-Mesh_1'].geometry} >
        <meshStandardMaterial color="#444444" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild002_Cube019-Mesh_2'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Cube006_Cube015-Mesh'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Cube006_Cube015-Mesh_1'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Wand001_Plane015-Mesh'].geometry} >
        <meshStandardMaterial color="#e0e0e0" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Wand001_Plane015-Mesh_1'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Wand1_Plane006-Mesh'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Wand1_Plane006-Mesh_1'].geometry} >
        <meshStandardMaterial color="#b22222" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Wand1_Plane006-Mesh_2'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Fenster_Plane003-Mesh'].geometry} >
        <meshStandardMaterial {...woodTextures} bumpScale={0.01} color="#aa7755" />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Fenster_Plane003-Mesh_1'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas002_Cylinder005-Mesh'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas002_Cylinder005-Mesh_1'].geometry} >
        <meshStandardMaterial color="#d2691e" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas001_Cylinder004-Mesh'].geometry} >
        <meshStandardMaterial color="#d2691e" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas001_Cylinder004-Mesh_1'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas_Cylinder002-Mesh'].geometry} >
        <meshStandardMaterial color="#d2691e" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Glas_Cylinder002-Mesh_1'].geometry} >
        <meshStandardMaterial color="#94a89a" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild001_Cube009-Mesh'].geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild001_Cube009-Mesh_1'].geometry} >
        <meshStandardMaterial color="#444444" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild001_Cube009-Mesh_2'].geometry} >
        <meshStandardMaterial color="#1A1A1A" roughness={0.6} metalness={0.3} />
        <FrameText geom={nodes['bild001_Cube009-Mesh_2'].geometry} text={"Available\nfor Hire"} color="#00ffaa" fontSize={0.06} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild_Cube007-Mesh'].geometry} >
        <meshStandardMaterial color="#ffd700" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild_Cube007-Mesh_1'].geometry} >
        <meshStandardMaterial color="#555555" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild_Cube007-Mesh_2'].geometry} >
        <meshStandardMaterial color="#111111" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['bild_Cube007-Mesh_3'].geometry} >
        <meshStandardMaterial color="#0A192F" roughness={0.6} metalness={0.3} />
        <FrameText geom={nodes['bild_Cube007-Mesh_3'].geometry} text={"Software\nDeveloper"} color="#ffffff" fontSize={0.06} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Fernseher_Cube006-Mesh'].geometry} >
        <meshStandardMaterial color="#000000" roughness={0.7} metalness={0.1} />
      </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh castShadow receiveShadow geometry={nodes['Fernseher_Cube006-Mesh_1'].geometry} >
        <meshStandardMaterial color="#111111" roughness={0.2} metalness={0.8} />
        <AnimatedTVText geom={nodes['Fernseher_Cube006-Mesh_1'].geometry} />
      </mesh>
      </RigidBody>
    </group>
  )
}

function AnimatedTVText({ geom }) {
  const textRef = useRef();

  const { textPos, quaternion } = useMemo(() => {
    if (!geom.boundingBox) geom.computeBoundingBox();
    const center = geom.boundingBox.getCenter(new THREE.Vector3());
    
    let maxArea = 0;
    let bestNormal = new THREE.Vector3(0, 0, 1);
    const pos = geom.attributes.position.array;
    const ind = geom.index ? geom.index.array : null;
    const numFaces = ind ? ind.length / 3 : pos.length / 9;
    
    let vA = new THREE.Vector3(), vB = new THREE.Vector3(), vC = new THREE.Vector3();
    let ab = new THREE.Vector3(), ac = new THREE.Vector3();
    
    for (let i = 0; i < numFaces; i++) {
       if (ind) {
         vA.fromArray(pos, ind[i*3]*3);
         vB.fromArray(pos, ind[i*3+1]*3);
         vC.fromArray(pos, ind[i*3+2]*3);
       } else {
         vA.fromArray(pos, i*9);
         vB.fromArray(pos, i*9+3);
         vC.fromArray(pos, i*9+6);
       }
       ab.subVectors(vB, vA);
       ac.subVectors(vC, vA);
       let cross = new THREE.Vector3().crossVectors(ab, ac);
       let area = cross.length();
       if (area > maxArea) {
           maxArea = area;
           bestNormal.copy(cross).normalize();
       }
    }
    
    const offset = bestNormal.clone().multiplyScalar(0.015);
    const textPos = center.clone().add(offset);
    const quaternion = new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 0, 1), bestNormal);
    
    return { textPos, quaternion };
  }, [geom]);

  useFrame((state) => {
    if (textRef.current) {
      // Smooth pulsing effect like a digital display
      textRef.current.fillOpacity = 0.5 + Math.sin(state.clock.elapsedTime * 2.5) * 0.5;
    }
  });

  return (
    <Text
      ref={textRef}
      position={[textPos.x, textPos.y + 0.02, textPos.z]} 
      quaternion={quaternion}
      fontSize={0.12}
      color="#00ff00"
      anchorX="center"
      anchorY="middle"
      maxWidth={3}
      textAlign="center"
      depthOffset={-1}
    >
      I am Golam Ali.{"\n"}Welcome to my Portfolio.
    </Text>
  );
}

function FrameText({ geom, text, fontSize, color }) {
  const { textPos, quaternion } = useMemo(() => {
    if (!geom.boundingBox) geom.computeBoundingBox();
    const center = geom.boundingBox.getCenter(new THREE.Vector3());
    
    let maxArea = 0;
    let bestNormal = new THREE.Vector3(0, 0, 1);
    const pos = geom.attributes.position.array;
    const ind = geom.index ? geom.index.array : null;
    const numFaces = ind ? ind.length / 3 : pos.length / 9;
    
    let vA = new THREE.Vector3(), vB = new THREE.Vector3(), vC = new THREE.Vector3();
    let ab = new THREE.Vector3(), ac = new THREE.Vector3();
    
    for (let i = 0; i < numFaces; i++) {
       if (ind) {
         vA.fromArray(pos, ind[i*3]*3);
         vB.fromArray(pos, ind[i*3+1]*3);
         vC.fromArray(pos, ind[i*3+2]*3);
       } else {
         vA.fromArray(pos, i*9);
         vB.fromArray(pos, i*9+3);
         vC.fromArray(pos, i*9+6);
       }
       ab.subVectors(vB, vA);
       ac.subVectors(vC, vA);
       let cross = new THREE.Vector3().crossVectors(ab, ac);
       let area = cross.length();
       if (area > maxArea) {
           maxArea = area;
           bestNormal.copy(cross).normalize();
       }
    }
    
    const offset = bestNormal.clone().multiplyScalar(0.015);
    const textPos = center.clone().add(offset);
    const quaternion = new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 0, 1), bestNormal);
    
    return { textPos, quaternion };
  }, [geom]);

  return (
    <Text
      position={[textPos.x, textPos.y, textPos.z]} 
      quaternion={quaternion}
      fontSize={fontSize || 0.12}
      color={color || "#ffffff"}
      anchorX="center"
      anchorY="middle"
      maxWidth={1.5}
      textAlign="center"
      depthOffset={-1}
    >
      {text}
    </Text>
  );
}

useGLTF.preload('/new_house.glb')
